### ISSUE TITLE
Error inflating class in fragment

### ISSUE THREAD

**Issue by loveydhillon** [Yalantis/ToDoList#15]
Error inflating class com.yalantis.beamazingtoday.ui.widget.BatRecyclerView

**Comment by gabrielkdc** [comment]
For what I see, it seems to be a problem with ButterKnife version

Caused by: java.lang.NoSuchMethodException: <init> [class com.yalantis.beamazingtoday.ui.widget.AddView, class android.view.View]
                                                                at java.lang.Class.getConstructor0(Class.java:2320)
                                                                at java.lang.Class.getConstructor(Class.java:1725)
                                                                at butterknife.ButterKnife.findBindingConstructorForClass(ButterKnife.java:231)
